### ISSUE TITLE
[Bug]: Nessie GC is not deleting files from S3 bucket after GC/delete command (expiry and orphan file clean up)

### ISSUE THREAD

**Issue by schobe** [projectnessie/nessie#9042] opened 2024-07-08 23:11 UTC
### What happened

Hi team,

We are trying to expire the old snapshots and delete the orphan files using the Nessie GC feature. Iceberg tables are created on top of s3 bucket, so after nessie gc we are expecting the expired files (data as well as metadata) to be deleted from the s3. However, the physical files are not deleted even after trying gc as well as explicit delete commands. Furthermore, we encountered following error while running nessie gc.

_Caused by: java.lang.RuntimeException: Failed to get paths from manifest file location.avro
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.allDataAndDeleteFiles(IcebergContentToFiles.java:225)
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.lambda$allManifestsAndDataFiles$2(IcebergContentToFiles.java:202)

Caused by: java.lang.IllegalArgumentException: Cannot parse partition spec fields, not an array: {"spec-id":0,"fields":[]}_

Can you please help us to understand this issue?  

### How to reproduce it

1. Create Iceberg table on s3 using Iceberg rest via Nessie (hosted via docker container)
2. Add some records in the table.
3. Get current snapshot id. 
4. Delete records from the table
5. Get current snapshot id. 
6. Run the following docker container to run the nessie GC. 
```
 nessie-gc:
    image: ghcr.io/projectnessie/nessie-gc:0.91.2
    ports:
      - "5435:5435"
    depends_on:
      nessie:
        condition: service_healthy
    command: gc --uri http://nessie:19120/api/v2 --iceberg=s3.access-key-id=${S3_KEY} --iceberg=s3.secret-access-key=${S3_SECRET} --jdbc --jdbc-url=${JDBC_URL} --jdbc-user=${JDBC_USERNAME} --jdbc-password=${JDBC_PASSWORD}
```
7. Check the gc log, docker logs container-id
8. Check the postgres tables if the references and live sets are deleted or not.
9. Check the s3 location if the expired or files marked as delete are deleted or not. 

                                                                                             

### Nessie server type (docker/uber-jar/built from source) and version

ghcr.io/projectnessie/nessie:0.90.4

**Comment by dimas-b** [comment] 2024-07-08 23:42
@schobe : Could you share the full exception stack trace, please?

**Comment by schobe** [comment] 2024-07-09 05:06
Sure, PFB the exception log

2024-07-08 21:52:10,797 [ForkJoinPool-3-worker-4] INFO  org.apache.iceberg.CatalogUtil - Loading custom FileIO implementation: org.apache.iceberg.aws.s3.S3FileIO
java.lang.RuntimeException: java.lang.RuntimeException: Failed to get paths from manifest file s3://manifestfilelocation.avro
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
        at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653)
        at java.base/java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2822)
        at org.projectnessie.gc.expire.local.DefaultLocalExpire.expire(DefaultLocalExpire.java:73)
        at org.projectnessie.gc.tool.cli.commands.BaseRepositoryCommand.expire(BaseRepositoryCommand.java:250)
        at org.projectnessie.gc.tool.cli.commands.MarkAndSweep.call(MarkAndSweep.java:57)
        at org.projectnessie.gc.tool.cli.commands.BaseRepositoryCommand.call(BaseRepositoryCommand.java:84)
        at org.projectnessie.gc.tool.cli.commands.BaseCommand.call(BaseCommand.java:26)
        at org.projectnessie.gc.tool.cli.commands.BaseCommand.call(BaseCommand.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.projectnessie.gc.tool.cli.CLI.runMain(CLI.java:103)
        at org.projectnessie.gc.tool.cli.CLI.runMain(CLI.java:75)
        at org.projectnessie.gc.tool.cli.CLI.main(CLI.java:70)
Caused by: java.lang.RuntimeException: Failed to get paths from manifest file s3://manifestfilelocation.avro
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.allDataAndDeleteFiles(IcebergContentToFiles.java:225)
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.lambda$allManifestsAndDataFiles$2(IcebergContentToFiles.java:202)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at org.projectnessie.gc.contents.jdbc.JdbcHelper$ResultSetSplit.tryAdvance(JdbcHelper.java:143)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
        at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
        at org.projectnessie.gc.expire.PerContentDeleteExpired.identifyLiveFiles(PerContentDeleteExpired.java:136)
        at org.projectnessie.gc.expire.PerContentDeleteExpired.expire(PerContentDeleteExpired.java:73)
        at org.projectnessie.gc.expire.local.DefaultLocalExpire.expireSingleContent(DefaultLocalExpire.java:104)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1395)
        at java.base/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:2104)
        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:420)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:668)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
        at org.projectnessie.gc.expire.local.DefaultLocalExpire.expireInForkJoinPool(DefaultLocalExpire.java:91)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.IllegalArgumentException: Cannot parse partition spec fields, not an array: {"spec-id":0,"fields":[]}
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
        at org.apache.iceberg.PartitionSpecParser.buildFromJsonFields(PartitionSpecParser.java:123)
        at org.apache.iceberg.PartitionSpecParser.fromJsonFields(PartitionSpecParser.java:114)
        at org.apache.iceberg.PartitionSpecParser.lambda$fromJsonFields$4(PartitionSpecParser.java:119)
        at org.apache.iceberg.util.JsonUtil.parse(JsonUtil.java:98)
        at org.apache.iceberg.PartitionSpecParser.fromJsonFields(PartitionSpecParser.java:119)
        at org.apache.iceberg.ManifestReader.readPartitionSpec(ManifestReader.java:130)
        at org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:114)
        at org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:132)
        at org.apache.iceberg.ManifestFiles.open(ManifestFiles.java:244)
        at org.apache.iceberg.ManifestReaderUtil.readPathsFromManifest(ManifestReaderUtil.java:29)
        at org.projectnessie.gc.iceberg.IcebergContentToFiles.allDataAndDeleteFiles(IcebergContentToFiles.java:222)
        ... 57 more

**Comment by snazy** [comment] 2024-07-09 11:20
Your manifest file is invalid/broken (not Iceberg spec compliant).

The stack trace indicates that the Avro meta attribute `partition-spec` contains the JSON `{"spec-id":0,"fields":[]}`, but that must only contain the fields array ([see here](https://github.com/apache/iceberg/blob/cbb853073e681b4075d7c8707610dceecbee3a82/core/src/main/java/org/apache/iceberg/ManifestReader.java#L130) and [here](https://github.com/apache/iceberg/blob/cbb853073e681b4075d7c8707610dceecbee3a82/core/src/main/java/org/apache/iceberg/PartitionSpecParser.java#L123)). Not sure who or what wrote the manifest files, but the issue is not in Nessie GC but in the code/software that wrote this manifest file.

The exception happens within Apache Iceberg code, where Nessie directly cannot do anything. But the exception is legit.

In fact, failing hard here is maybe not nice, but the best option IMHO, because if Nessie GC would continue (and silently ignore the exception), it could delete files which are still in use.

My recommendation is to open a bug with the vendor/project that wrote this invalid/broken manifest file.

**Comment by schobe** [comment] 2024-07-09 14:25
@snazy , Thanks for the inputs on this issue. We also tried using nessie delete with an explicit live set id for a different table. We deleted some records/partitions from the table, and then ran Nessie gc which completed the identify, sweep step but failed due to above error in one of the table. 

Then we tried running nessie delete from other table where we deleted data/partitions. Nessie delete was completed successfully with following message, but it did not delete physical files from s3. What would be the reason of not deleting the expired/orphan files in this case? 

```
22:58:51,400 |-INFO in ch.qos.logback.classic.util.ContextInitializer@1189dd52 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 92 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY
Deleting live content set 0552be4f-4640-409d-97e9-6f3e1c549188
Timestamps shown in UTC
ID                                    Status                  Created                   Identify complete         Expiry started            Expiry finished           Error
0552be4f-4640-409d-97e9-6f3e1c549188  EXPIRY_SUCCESS          2024-07-08T21:44:08       2024-07-08T21:45:28       2024-07-08T21:45:28       2024-07-08T21:46:36       
Live content set 0552be4f-4640-409d-97e9-6f3e1c549188successfully deleted.
```

**Comment by snazy** [comment] 2024-07-09 16:25
It did what `delete` is supposed to do, just delete the live-set in the database. That's not `sweep`/`expire`

**Comment by snazy** [comment] 2024-07-15 08:57
@schobe do you know which tool/software produced the manifests?

**Comment by schobe** [comment] 2024-07-15 15:58
@snazy , We used pyiceberg to produce these manifest files. We checked the scenario where this issue is happening, and looks like this is happening when we just create table and drop it without loading data. In that case, only metadata folder is available for the table. Do you think this is a limitation on gc right now? And another thing we observed that, even if the nessie gc command fails with this error, the live content set table is updated with value Expiry Success without any error logged in the table.

**Comment by snazy** [comment] 2024-07-18 09:49
> We used pyiceberg to produce these manifest files. We checked the scenario where this issue is happening, and looks like this is happening when we just create table and drop it without loading data. In that case, only metadata folder is available for the table. Do you think this is a limitation on gc right now?

Just the creation of a table does not generate manifest files - the issue you reported happens with _invalid_ manifest files. We do not know which software produced these invalid manifest files - maybe it is pyiceberg, but we do not know.
Nothing to do with Nessie GC.

> And another thing we observed that, even if the nessie gc command fails with this error, the live content set table is updated with value Expiry Success without any error logged in the table.

Fixed by #9114

**Comment by snazy** [comment] 2024-07-18 12:54
pyiceberg caused the broken manifest files - see https://github.com/apache/iceberg-python/pull/846

**Comment by snazy** [comment] 2024-07-18 13:19
Oh - and pyiceberg still does even in its latest version. In other words: manifest files written by pyiceberg may be unreadable by iceberg/java. Will add a workaround via #9131.

**Closed** 2024-07-18 13:26 UTC
