### ISSUE TITLE
Health check / CDI scope mismatch

### ISSUE THREAD

**Issue by venkata2395** [projectnessie/nessie#9852] opened 2024-10-31 13:26 UTC
### Issue description

We noticed below issue when using Nessie snapshot version - 0.99.1. This appears only during the nessie startup log but works fine with the read/write operations later when pod is ready. Please provide insights on how to overcome this issue.

```
2024-10-30 14:12:22,387 INFO  [org.pro.qua.pro.sto.PersistProvider] (main) Using objects cache with 13694 MB, enabling distributed cache invalidations.
2024-10-30 14:12:22,571 INFO  [com.dat.oss.dri.int.cor.DefaultMavenCoordinates] (main) DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.15.0
2024-10-30 14:12:23,010 INFO  [com.dat.oss.dri.int.cor.tim.Clock] (vert.x-eventloop-thread-1) Using native clock for microsecond precision
2024-10-30 14:12:25,153 INFO  [org.pro.qua.pro.sto.PersistProvider] (main) Creating/opening version store CASSANDRA2 ...
2024-10-30 14:12:25,156 INFO  [org.pro.qua.pro.sto.PersistProvider] (main) Using CASSANDRA2 version store (keyspace: xxxx DDL timeout: PT5S DML timeout: PT3S)
2024-10-30 14:12:25,157 WARN  [org.pro.ser.con.ConfigChecks] (main) Both authentication (AuthN) and authorization (AuthZ) are disabled, all requests to Nessie will be permitted. This means: everybody with access to Nessie can read, write and change everything. Recommended action: Enable AuthN & AuthZ, see https://projectnessie.org/nessie-latest/configuration/
2024-10-30 14:12:25,167 INFO  [org.pro.ser.cat.sec.SecretsProducers] (main) No external secrets manager has been configured, secrets are retrieved only from the Quarkus configuration.
2024-10-30 14:12:25,477 INFO  [org.pro.nes.net.AddressResolver] (main) Using nameserver kube-dns.kube-system.svc.cluster.local with search list [nessie.svc.cluster.local, svc.cluster.local, cluster.local, reddog.microsoft.com]
2024-10-30 14:12:25,523 INFO  [org.pro.ser.dis.CacheInvalidationSender] (main) Sending remote cache invalidations to service name(s) [nessie-mgmt]
2024-10-30 14:12:25,619 INFO  [io.quarkus] (main) Nessie 0.99.1-SNAPSHOT on JVM (powered by Quarkus 3.15.1) started in 7.642s. Listening on: http://0.0.0.0:19120. Management interface listening on http://0.0.0.0:9000.
2024-10-30 14:12:25,620 INFO  [io.quarkus] (main) Profile prod activated.
2024-10-30 14:12:25,620 INFO  [io.quarkus] (main) Installed features: [agroal, amazon-dynamodb, amazon-secretsmanager, azure-keyvault-secret, cassandra-client, cdi, google-cloud-bigtable, google-cloud-secret-manager, hibernate-validator, jdbc-h2, jdbc-mariadb, jdbc-postgresql, logging-sentry, micrometer, mongodb-client, narayana-jta, oidc, opentelemetry, reactive-routes, rest, rest-jackson, security, security-properties-file, smallrye-context-propagation, smallrye-health, smallrye-openapi, vault, vertx]
2024-10-30 14:12:27,674 ERROR [io.sma.health] (executor-thread-3) SRHCK01000: Error processing Health Checks: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=org.projectnessie.server.catalog.ConfigProducers, id=xxxxxxxxxxxxxxx]
- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
    at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
    at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
    at org.projectnessie.catalog.service.config.ConfigProducers_ProducerMethod_lakehouseConfig_iH0TIfcbanSdrPA9ouxuYH35T1A_ClientProxy.arc$delegate(Unknown Source)
    at org.projectnessie.catalog.service.config.ConfigProducers_ProducerMethod_lakehouseConfig_iH0TIfcbanSdrPA9ouxuYH35T1A_ClientProxy.catalog(Unknown Source)
```

Health check log provided below:

```
2024-10-30 14:12:27,683 INFO  [io.sma.health] (vert.x-eventloop-thread-7) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Database connections health check","status":"UP"},{"name":"MongoDB connection health check","status":"UP"},{"name":"org.projectnessie.server.catalog.ObjectStoresHealthCheck_ClientProxy","status":"DOWN","data":{"exceptionClass":"jakarta.enterprise.context.ContextNotActiveException","exceptionMessage":"RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=org.projectnessie.server.catalog.ConfigProducers, id=xxxxxx]\n\t- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding","rootCause":"RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=org.projectnessie.server.catalog.ConfigProducers, id=xxxx]\n\t- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding"}}]}
```

**Comment by snazy** [comment] 2024-11-04 19:03
@venkata2395 I fear we need a full reproducer for this one. We cannot reproduce it.

**Comment by adutra** [comment] 2024-11-18 10:32
Another occurrence, but this time when calling `ObjectIO.ping()`:

```
2024-11-13 10:04:31,661 ERROR [org.pro.ser.cat.ObjectStoresHealthCheck] (executor-thread-1) Failed to ping warehouse 'nessie-playground', error ID f814a805-3e4d-4101-8e9f-b339d684d7a2: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=org.projectnessie.server.catalog.CatalogProducers, id=IoYBgW3_kRGTU-USRbZWANKDXPA]
    - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
    at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
    at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
    at org.projectnessie.catalog.files.api.CatalogProducers_ProducerMethod_objectIO_Ed95GkFIhtTZERiabosXvHelB7Q_ClientProxy.arc$delegate(Unknown Source)
    at org.projectnessie.catalog.files.api.CatalogProducers_ProducerMethod_objectIO_Ed95GkFIhtTZERiabosXvHelB7Q_ClientProxy.ping(Unknown Source)
    at org.projectnessie.server.catalog.ObjectStoresHealthCheck.call(ObjectStoresHealthCheck.java:61)
```

**Comment by adutra** [comment] 2024-11-18 10:37
I wonder if `ObjectStoresHealthCheck` shouldn't be annotated with `@RequestScoped` instead of `@ApplicationScoped`.

**Comment by adutra** [comment] 2024-12-02 11:25
Another occurrence on minikube, running locally:

```
2024-12-02 11:02:11,642 ERROR [io.sma.health] (executor-thread-1) SRHCK01000: Error processing Health Checks: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=org.projectnessie.server.catalog.ConfigProducers, id=dh9_0qKUXfXc7Z1TQCToTu4cjkc]
        - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
        at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
        at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
        at org.projectnessie.catalog.service.config.ConfigProducers_ProducerMethod_lakehouseConfig_iH0TIfcbanSdrPA9ouxuYH35T1A_ClientProxy.arc$delegate(Unknown Source)
        at org.projectnessie.catalog.service.config.ConfigProducers_ProducerMethod_lakehouseConfig_iH0TIfcbanSdrPA9ouxuYH35T1A_ClientProxy.catalog(Unknown Source)
        at org.projectnessie.server.catalog.ObjectStoresHealthCheck.call(ObjectStoresHealthCheck.java:55)
        at org.projectnessie.server.catalog.ObjectStoresHealthCheck_ClientProxy.call(Unknown Source)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.smallrye.health.runtime.QuarkusAsyncHealthCheckFactory$1$1.call(QuarkusAsyncHealthCheckFactory.java:42)
        at io.quarkus.smallrye.health.runtime.QuarkusAsyncHealthCheckFactory$1$1.call(QuarkusAsyncHealthCheckFactory.java:39)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

What may be happening is that the health check is executed on a separate thread than the one that handled the incoming request, see `QuarkusAsyncHealthCheckFactory.callSync()` – because `ObjectStoresHealthCheck` implements the (synchronous) `HealthCheck` interface rather than `AsyncHealthCheck`.

According to [the docs on context propagation](https://quarkus.io/guides/context-propagation#context-propagation-for-cdi), this is dangerous for request-scoped beans because if the original request finishes too soon, the beans associated with it will be destroyed before they are accessed by the health-check thread. This seems to correspond to what we see and explain why it doesn't happen all the time.

Moreover, I see in the [docs on health checks](https://quarkus.io/guides/smallrye-health#context-propagation-into-the-health-check-invocations) that:

> For performance reasons, the context (e.g., CDI or security context) is not propagated into each health check invocation. However, if you need to enable this functionality you can set the config property `quarkus.smallrye-health.context-propagation=true` to allow the context propagation into every health check call.

I'm not sure this is entirely true, because at least the application-scoped beans are present all the time when the health check executes.

We could try to add `quarkus.smallrye-health.context-propagation=true` though, and see if that option also propagates request-scoped beans safely.

**Comment by dimas-b** [comment] 2024-12-02 14:52
> [...] it doesn't make sense to use request-scoped beans in a health check

I agree. I think it works ATM because the referenced request-scoped beans (`LakehouseConfig`) are in fact request-independent. That is a static `LakehouseConfig` is used.

If/when we store `LakehouseConfig` in the database, it will probably lead to real errors.

I think the health check should rather verity _all_ `LakehouseConfig` objects, which would then be a proper application-scoped collection (or producer). WDYT?

**Comment by dimas-b** [comment] 2024-12-02 16:01
I think using `quarkus.smallrye-health.context-propagation=true` is a good fix for this specific issue.

Still, I am not convinced that it will work correctly when `LakehouseConfig` is not static, but loaded from storage based on user-provided data (e.g. repository ID).

**Comment by adutra** [comment] 2024-12-02 16:57
> I am not convinced that it will work correctly when LakehouseConfig is not static, but loaded from storage based on user-provided data (e.g. repository ID).

Indeed, `LakehouseConfigManagement` is ultimately dependent on the repository ID. We could maybe iterate over all repository IDs and check them all, but I wonder if that wouldn't become a bit overkill for a health check. @snazy wdyt?

**Comment by dimas-b** [comment] 2024-12-02 17:12
I'd say let's add a config for the list of repository IDs the admin user wants in the health check.

The check itself is useful because of #8860

In most situations, I think it's going to be one per server.

**Closed** 2024-12-03 08:55 UTC
