### ISSUE TITLE
Merging branches doesn't show any author name 

### ISSUE THREAD

**Issue by mthirani2021** [projectnessie/nessie#6956] opened 2023-06-01 20:40 UTC
While trying to merge a branch "branchdemo" into "main", it seems there is no default author name added (not being sent as response)

**What happened**:
Tried to merge a branch into main using the below API and request payload:
POST `trees/main%4058346f07f41dd2033082cec7be5311010b1644febb19c016777a44c4752cac25/history/merge`

`{"fromRefName":"branchdemo","fromHash":"621f99726e4263a32eedf80c2270c739054407adf0e4759518fb61670465b3f7"}`

Response:
```
{
    "wasApplied": true,
    "wasSuccessful": true,
    "resultantTargetHash": "521c292e2b39a032fdd57c421d488120b90741c6560e9cebf470fbbb73d13ad2",
    "commonAncestor": "1b91af97348ae86e388e355c144409279bca48698454d8fcda4e197e09aac251",
    "targetBranch": "main",
    "effectiveTargetHash": "58346f07f41dd2033082cec7be5311010b1644febb19c016777a44c4752cac25",
    "expectedHash": "58346f07f41dd2033082cec7be5311010b1644febb19c016777a44c4752cac25",
    "details": []
}
```

**What you expected to happen**:
Response should contain the author name (defaulted to original user probably)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a common commit before creating a branch from main
2. Create a branch from main
3. Create a commit in branch (make sure that it has authorname passed to API) 
4. Merge the branch into main

**Details**:
- Nessie server type (docker/built from source) and version: 0.60.1
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by mthirani2021** [comment] 2023-06-01 20:40
@dimas-b FYI

**Comment by snazy** [comment] 2023-06-02 12:05
`org.projectnessie.model.MergeResponse` is defined to not contain any commit details - it returns the commit-ID of the merge commit. Note that we cannot change `MergeResponse`, because REST API v2 is declared "GA" now.

**Comment by mthirani2021** [comment] 2023-06-02 13:57
I was expecting to get authorname in log entries response (if not in merge response).

Response for log entries looks like below:

GET `/trees/main/history?fetch=MINIMAL&filter=&max-records=50`

```
"logEntries": [
        {
            "commitMeta": {
                "hash": "dc793cd98254599e6be62ceb8f6c37e077c5afd913658c53883da34f6d92072d",
                "committer": "",
                "authors": [
                    ""
                ],
                "allSignedOffBy": [],
                "message": "Merged 3 commits from branchdemo at 68aebedb4981a6d023891c683f6e90ef38370be2a9be2c7101937efbc0f5349d into main at de378be9b84046e8b2ab6d8ed9e59f6548d2e7c340aa0618c21cb600b26164aa",
                "commitTime": "2023-06-01T18:23:29.242269960Z",
                "authorTime": "2023-06-01T18:23:29.242269960Z",
                "allProperties": {
                    "_merge_parent": [
                        "68aebedb4981a6d023891c683f6e90ef38370be2a9be2c7101937efbc0f5349d"
                    ]
                },
                "parentCommitHashes": [
                    "de378be9b84046e8b2ab6d8ed9e59f6548d2e7c340aa0618c21cb600b26164aa",
                    "68aebedb4981a6d023891c683f6e90ef38370be2a9be2c7101937efbc0f5349d"
                ]
            },
            "parentCommitHash": "de378be9b84046e8b2ab6d8ed9e59f6548d2e7c340aa0618c21cb600b26164aa"
        }
```

**Comment by snazy** [comment] 2023-06-02 14:06
Do other commits have author & committer information?

**Comment by dimas-b** [comment] 2023-06-05 17:03
@mthirani2021 : This should have been fixed by #6641 , but #4562 may be interfering.

Could you please re-test with the latest Nessie release and do just _one_ merge?

**Comment by mthirani2021** [comment] 2023-06-05 17:15
@dimas-b the behavior is same with one merge too.

**Comment by mthirani2021** [comment] 2023-06-13 14:20
@dimas-b any updates on this one ?

**Comment by dimas-b** [comment] 2023-06-13 14:34
Confirmed. Author data appears to be lost on `merge`:

**Comment by dimas-b** [comment] 2023-06-13 17:01
Merging without providing an explicit "author" in the commit meta of the merge request does not propagate the authors from the commits being merged.

I believe it is quite reasonable for Nessie to fill in `authors` from the merge source commit, if an override is not specified.

**Closed** 2023-06-14 14:16 UTC

**Comment by mthirani2021** [comment] 2023-06-14 14:43
Should I be able to test this in next released version ?

**Comment by snazy** [comment] 2023-06-14 14:43
It's merged and will be included in 0.62.0+

**Comment by snazy** [comment] 2023-06-14 14:44
Also in the next published SNAPSHOT release

**Comment by mthirani2021** [comment] 2023-06-14 14:45
Got it, thanks!

**Comment by snazy** [comment] 2023-06-15 08:51
(Duplicating the comment from #7039) Note: the "pull information from merged commits" clashes with #7035 / #4562, because that will support merging "heavily nested trees" and identifying the "merged commits" would become extremely difficult. Therefore the new storage model will _only_ set the author to the committer.

**Comment by mthirani2021** [comment] 2023-06-15 12:40
We should be able to test in new storage model (default model) in OSS Nessie in 0.62.+? Is this what you mean here?
Also I see the PR #7039  gets removed from 0.62.0 Milestones so I am not sure if this means fix is not available in that version as well.

**Comment by mthirani2021** [comment] 2023-06-15 14:11
Yes I understand, but this is what I have tested with new storage model in 0.60.1 / 0.61.0 
and if you mean in 0.62.0 then I am seeing the dependent PR gets removed from Milestones.
So I am little confused here.

**Comment by mthirani2021** [comment] 2023-06-15 14:39
I see, to be clear this looks like a blocker to test until #7035 and #4562 gets done and then we can release the associated PR #7039

**Comment by mthirani2021** [comment] 2023-06-15 14:54
Got it; So just wait till #7035 and #4562 gets released.
