### ISSUE TITLE
[Bug]: [org.pro.qua.pro.sto.AddressResolver] (vert.x-eventloop-thread-1) Failed to resolve 'nessie-mgmt' to A/AAAA records: io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error

### ISSUE THREAD

**Issue by jordi-ydteam** [projectnessie/nessie#8840] opened 2024-06-15 12:17 UTC
### What happened

I have deployed nessie on my gke cluster.

When I deploy nessie to a namespace other than nessie, I get this error:

````

[org.pro.qua.pro.sto.AddressResolver] (vert.x-eventloop-thread-1) Failed to resolve 'nessie-mgmt' to A/AAAA records: io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error
````

If I deploy in the nessie namespace, it works correctly.

I think the nessie pod tries to look for the service directly in the nessie namespace instead of the namespace where the pod has been deployed. 

Could it be modified so that nessie can be deployed in any namespace?

### How to reproduce it

```
helm install --namespace default nessie nessie-helm/nessie
```

### Nessie server type (docker/uber-jar/built from source) and version

docker

### Client type (Ex: UI/Spark/pynessie ...) and version

UI, latest version

**Comment by snazy** [comment] 2024-06-17 07:59
Duplicate of #8829

**Closed by snazy** 2024-06-17 07:59 UTC
