### ISSUE TITLE
Ingress configuration not working when path is not root ("/")

### ISSUE THREAD

**Issue by julwin** [projectnessie/nessie#6836] opened 2023-05-15 10:18 UTC
**What happened**:

I am configuring nessie ingress like this using the helm chart:

```
ingress:
  enabled: true
  annotations:
    {
      "cert-manager.io/cluster-issuer": "my-acme",
      "traefik.ingress.kubernetes.io/router.middlewares": "nessie-nessie-mw@kubernetescrd",
    }
  hosts:
    [
      {
        "host": "my.domain.net",
        "paths": ["/nessie"],
      },
    ]
  tls:
    - hosts:
        - my.domain.net
      secretName: my.domain.net
```

Middleware:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nessie-mw
  namespace: nessie
spec:
  stripPrefix:
    prefixes:
      - /nessie
    forceSlash: false
```

Instead of showing the nessie frontend, I only get blank pages.

**What you expected to happen**:

Nessie being available on my domain at /nessie

**How to reproduce it (as minimally and precisely as possible)**:
Configure nessie ingress to use non-root paths.

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by adutra** [comment] 2023-07-10 09:21
Hi @julwin sorry for the very late reply.

I tried to reproduce the issue locally using minikube:


```shell
minikube start
minikube addons enable ingress
kubectl create ns nessie-ns
helm install traefik traefik/traefik -n nessie-ns

kubectl apply -f - <<EOF
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nessie-mw
  namespace: nessie-ns
spec:
  stripPrefix:
    prefixes:
      - /nessie
    forceSlash: false
EOF

cat <<EOF > nessie-values.yaml
ingress:
  enabled: true
  annotations:
    "traefik.ingress.kubernetes.io/router.middlewares": "nessie-ns-nessie-mw@kubernetescrd"
  hosts:
    - host: "nessie.local"
      paths: ["/nessie"]
EOF

helm install nessie -n nessie-ns nessie-helm/nessie --values nessie-values.yaml 
minikube tunnel
```

Then I could access Nessie under the `/nessie` path as expected:

```shell
 curl --resolve "nessie.local:80:127.0.0.1" http://nessie.local/nessie/api/v2/config           
{
  "defaultBranch" : "main",
  "minSupportedApiVersion" : 1,
  "maxSupportedApiVersion" : 2,
  "actualApiVersion" : 2,
  "specVersion" : "2.1.0",
  "noAncestorHash" : "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d",
  "repositoryCreationTimestamp" : "2023-07-10T09:13:33.653793590Z",
  "oldestPossibleCommitTimestamp" : "2023-07-10T09:13:33.653793590Z"
}%         
```                                                                                              

So I'm guessing whether the problem isn't in either:

- The Middleware `apiVersion`: I used `traefik.io/v1alpha1` according to the [docs](https://doc.traefik.io/traefik/middlewares/http/stripprefix/).
- A namespace problem? I deployed both Traefik and Nessie in the same namespace.
- A TLS problem? My attempts wasn't using TLS at all.

**Comment by adutra** [comment] 2023-07-25 17:26
Hi @julwin, I understand :-) Let's close this for now then, and feel free to re-open at any time! Cheers!

**Closed by adutra** 2023-07-25 17:26 UTC
