### ISSUE TITLE
ITSparkExtensions fail w/ Spark 3.3 + latest Iceberg

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#6114] opened 2023-02-16 13:46 UTC
Example CI run: https://github.com/projectnessie/query-engine-integration-tests/actions/runs/4190567702/jobs/7264100795

Example failure: https://scans.gradle.com/s/f3ywj2or6e6e6/tests/overview

**Comment by ajantha-bhat** [comment] 2023-02-16 13:47
ACK. Let me check it.

**Comment by ajantha-bhat** [comment] 2023-02-16 14:07
Analysis from the code review:

https://github.com/projectnessie/nessie/blob/31357d3f10e50515f7e40a0d75225b4f339ca1af/clients/spark-extensions-basetests/src/main/java/org/projectnessie/spark/extensions/AbstractNessieSparkSqlExtensionTest.java#L631

Yesterday this PR got merged (https://github.com/apache/iceberg/pull/6801) which introduces one more argument. Hence, the strict check fails. 

@snazy: We need to update the testcase when we bump the Iceberg version or shall I modify the test case now to loosen the check?

**Comment by ajantha-bhat** [comment] 2023-02-16 17:10
I have fixed all 4 test failures from the above build in https://github.com/projectnessie/nessie/pull/6117

But when I test locally (with the iceberg master), I do get some timeouts for a few tests (even without my fix).  Not sure about the cause yet. But the above build doesn't seem to have those errors.
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/5889404/219437660-2a6c1862-54e7-45a1-99db-74ec77243555.png">

**Comment by ajantha-bhat** [comment] 2023-02-17 04:52
Closing the ticket as the PR is merged and build is passing
https://github.com/projectnessie/query-engine-integration-tests/actions/runs/4200564588

**Closed by ajantha-bhat** 2023-02-17 04:52 UTC
