### ISSUE TITLE
Internal Server Error (500) instead of Bad Request (400) on malformed POST requests

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#3498] opened 2022-03-02 15:18 UTC
```
$ curl 'http://localhost:19120/api/v1/trees/tree?sourceRefName=main' -X POST -d '{"name": "test4", "metadata": null, "type": "BRANCH", "hash":"aaa"}'
{
  "status" : 500,
  "reason" : "Internal Server Error",
  "message" : "javax.ws.rs.NotSupportedException: RESTEASY003065: Cannot consume content type",
  "errorCode" : "UNKNOWN",
  "serverStackTrace" : null
}
```
The response should be BAD REQUEST (400)

**Comment by snazy** [comment] 2022-07-21 12:21
@dalaro this looks like a duplicate of #4436?

**Closed** 2022-07-21 14:58 UTC
