### ISSUE TITLE
Nessie Iceberg Demo doesn't work with Spark 3.1.1

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#1188] opened 2021-05-05 13:34 UTC
**What happened**:
When going through the Nessie Iceberg demo from https://github.com/projectnessie/nessie/blame/main/python/demo/nessie-iceberg-demo.ipynb, things would fail at https://github.com/projectnessie/nessie/blame/main/python/demo/nessie-iceberg-demo.ipynb#L143 with the following exception

```
AnalysisException                         Traceback (most recent call last)
<ipython-input-5-1ce6157307c7> in <module>
     12 region_table = catalog.createTable(region_name, region_schema, region_spec)
     13 region_df = spark_dev.read.load("data/region.parquet")
---> 14 region_df.write.format("iceberg").mode("overwrite").save("nessie.testing.region")
     15 
     16 # Creating nation table

~/Development/workspace/nessie/python/demo/venv/lib/python3.8/site-packages/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    828             self._jwrite.save()
    829         else:
--> 830             self._jwrite.save(path)
    831 
    832     @since(1.4)

~/Development/workspace/nessie/python/demo/venv/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

~/Development/workspace/nessie/python/demo/venv/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    132                 # Hide where the exception came from that shows a non-Pythonic
    133                 # JVM exception message.
--> 134                 raise_from(converted)
    135             else:
    136                 raise

~/Development/workspace/nessie/python/demo/venv/lib/python3.8/site-packages/pyspark/sql/utils.py in raise_from(e)

AnalysisException: Table testing.region not found
```

After investigating the Nessie server logs, one could see that creating the table succeeded via `POST /api/v1/contents/testing.region?branch=dev&hash=5d1e09785da83245caf91d53c8d8c5b753ef21ca&message=iceberg%20commit HTTP/1.1" 204 -`:
```
nessie_1    | 2021-05-05 06:29:15,128 INFO  [io.qua.htt.access-log] (executor-thread-1) 172.18.0.1 - - 05/May/2021:06:29:15 +0000 "POST /api/v1/contents/testing.region?branch=dev&hash=5d1e09785da83245caf91d53c8d8c5b753ef21ca&message=iceberg%20commit HTTP/1.1" 204 -
nessie_1    | 2021-05-05 06:29:17,005 INFO  [io.qua.htt.access-log] (executor-thread-1) 172.18.0.1 - - 05/May/2021:06:29:17 +0000 "GET /api/v1/trees/tree/main HTTP/1.1" 200 97
nessie_1    | 2021-05-05 06:29:17,024 INFO  [io.qua.htt.access-log] (executor-thread-1) 172.18.0.1 - - 05/May/2021:06:29:17 +0000 "GET /api/v1/trees/tree/main HTTP/1.1" 200 97
nessie_1    | 2021-05-05 06:29:17,033 INFO  [io.qua.htt.access-log] (executor-thread-1) 172.18.0.1 - - 05/May/2021:06:29:17 +0000 "GET /api/v1/trees/tree/main HTTP/1.1" 200 97
nessie_1    | 2021-05-05 06:29:17,046 INFO  [io.qua.htt.access-log] (executor-thread-1) 172.18.0.1 - - 05/May/2021:06:29:17 +0000 "GET /api/v1/contents/testing.region?ref=5d1e09785da83245caf91d53c8d8c5b753ef21ca HTTP/1.1" 404 149
```
However, an immediate `GET` would fail (`GET /api/v1/contents/testing.region?ref=5d1e09785da83245caf91d53c8d8c5b753ef21ca HTTP/1.1" 404 149`. It seems that the `ref` is still pointing to the `main` branch, while it actually should point to the `dev` branch.

The problem can be worked around with 
```
@@ -129,6 +129,9 @@
    "source": [
     "catalog = jvm.CatalogUtil.loadCatalog(\"org.apache.iceberg.nessie.NessieCatalog\", \"nessie\", {'ref': 'dev', 'url': 'http://localhost:19120/api/v1', \"warehouse\": 'file://' + os.getcwd() + '/spark_warehouse'}, sc._jsc.hadoopConfiguration())\n",
     "\n",
+    "# FIXME: just a WORKAROUND as somehow we're ending up using the \"main\" nessie ref\n",
+    "spark.conf.set(\"spark.sql.catalog.nessie.ref\", \"dev\")\n",
+    "\n",
     "# Creating region table\n",
     "region_name = jvm.TableIdentifier.parse(\"testing.region\")\n",
     "region_schema = jvm.Schema([\n",
```
The root cause seems to be that `spark.sql.catalog.nessie.ref` is still pointing to `main` and not to `dev` as I was able to verify this by adding a `spark_dev.sparkContext.getConf().getAll()`. 

**What you expected to happen**:
Demo from https://github.com/projectnessie/nessie/blame/main/python/demo/nessie-iceberg-demo.ipynb passing successfully with the latest Spark 3 version (which is `3.1.1` as of this writing)

**How to reproduce it (as minimally and precisely as possible)**:
Run the Demo from https://github.com/projectnessie/nessie/blame/main/python/demo/nessie-iceberg-demo.ipynb with `SPARK_HOME` pointing to a Spark version `3.1.1`

**Details**:
- Nessie server type (docker/built from source) and version: Nessie set up as described in the Demo readme, using `0.5.1.`
- Client type (Ex: UI/Spark/pynessie ...) and version: PySpark/pynessie

**Comment by rymurr** [comment] 2021-05-05 13:38
See https://github.com/apache/iceberg/pull/2512

The 0.12.0 release of iceberg will support Spark 3.1

**Comment by nastra** [comment] 2021-05-05 13:52
@rymurr thanks for linking the issue. Since the demo didn't specify an explicit spark version, I went with the latest and hence the ticket.

**Comment by nastra** [comment] 2021-05-17 15:33
@snazy I believe you fixed this already?

**Comment by nastra** [comment] 2021-06-09 07:50
This was fixed by https://github.com/projectnessie/nessie-demos/blame/037edef87283cf524c6cc8d4ebc861b5b5886360/pydemolib/nessiedemo/iceberg_spark.py#L92-L93

**Comment by rymurr** [comment] 2021-06-09 07:54
Im not sure that fixes it. It changes the active spark session which might
not be what we want. We want multiple (potentially) active sessions.


I don't want to use the demo on spark 3.1 until iceberg releases 0.12.0 to
fix compatibility. There are a number of other potential bugs in
Spark3.1/iceberg 0.11.1

**Comment by rymurr** [comment] 2021-06-09 07:55
I guess we can close this. The issue is not w/ Nessie.

**Closed** 2021-06-09 07:55 UTC
