### ISSUE TITLE
Same table path having multiple tables files from all the branches. 

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#4285] opened 2022-05-20 06:18 UTC
I just observed that,
Create branch_1 from main and then create a table_1 on this branch with columns A, B and do some insert.
Create branch_2 from main and then create a table_1 on this branch with columns X,Y,Z and do some insert.

They both share the same table location even though it is different tables :warning: (the warehouse location is the same). 
Running remove orphan_files on table_1 on branch_1 cleans the table_1 on branch_2 completely and leads to an error. 

Any thoughts on this scenario? some other branch's table files are coming to my table path just because the warehouse location is the same (or unknowingly configured same). 

steps:
```
docker run -p 19120:19120 projectnessie/nessie

                              
 /Users/ajantha/Documents/tools/spark-3.0.3-bin-hadoop2.7/bin/spark-sql --packages org.slf4j:slf4j-api:1.7.32 --jars /Users/ajantha/Downloads/iceberg-spark-runtime-3.0_2.12-0.14.0-SNAPSHOT.jar,/Users/ajantha/Downloads/nessie-spark-extensions-0.28.0.jar \
                                    --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog\
                                    --conf spark.sql.catalog.nessie.warehouse=$PWD/nessie2 \
                                --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog \
                                --conf spark.sql.catalog.nessie.uri=http://localhost:19120/api/v1 \
                                --conf spark.sql.catalog.nessie.ref=main \
                                --conf spark.sql.catalog.nessie.auth-type=NONE \
                                --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
```

```
create branch dev in nessie from main;

use reference dev in nessie;

create table nessie.db1.t1(id int) using iceberg;
insert into nessie.db1.t1 select 42;

use reference main in nessie;

create table nessie.db1.t1(place string, name string) using iceberg;
insert into nessie.db1.t1 select 'x','y';
```

**Comment by ajantha-bhat** [comment] 2022-05-20 06:55
Some observations with hive catalog:
1. create table with `location` syntax will give an error if the folder is not empty.
2. Normal create table syntax will create a table even if the folder is not empty and orphan files will clean those old files. 
But it is unlikely the LIVE table's files as HiveCatalog cannot two live tables with the same name. But Nessie can have it.

**Comment by ajantha-bhat** [comment] 2022-05-20 07:20
So far, (without global state) I only thought running `remove_orphan` files on the table_x at branch_y might clean the files of the same table which are referenced in other branches. Now it can clean some other table data also which is also problematic. 

With all these problems we need to figure out how to remove orphan files created for Iceberg table with the Nessie catalog.

**Comment by snazy** [comment] 2022-05-20 08:25
That's a duplicate of #1925

**Comment by snazy** [comment] 2022-05-20 08:30
On the Iceberg side, the table's folder name should probably be `<table-name>-<table-uuid>`.

**Comment by ajantha-bhat** [comment] 2022-05-20 08:41
> That's a duplicate of https://github.com/projectnessie/nessie/issues/1925 ?
Fixing orphan files is same as this. 
We can use this issue to fix table path in the nessie catalog. 

> On the Iceberg side, the table's folder name should probably be <table-name>-<table-uuid>.
Yeah, I had the same fix in mind. I will explore this.

**Comment by snazy** [comment] 2022-05-20 08:58
Actually, it should really be `<table-name>-<ANOTHER-RANDOM-UUID>` - otherwise importing the same iceberg table into two different branches would run into the same problem.

**Comment by ajantha-bhat** [comment] 2022-05-20 14:56
> Actually, it should really be <table-name>-<ANOTHER-RANDOM-UUID> - otherwise importing the same iceberg table into two different branches would run into the same problem.

I didn't get it. Isn't importing the same table in two different branches suppose to share the same folder location? Same as how currently if the same table exists in two branches it shares the same table with table UUID.

**Comment by ajantha-bhat** [comment] 2022-05-20 14:56
https://github.com/apache/iceberg/pull/4826

**Comment by snazy** [comment] 2022-05-31 07:22
Independently importing the same Iceberg table-metadata into two different branches means two different tables.

**Comment by snazy** [comment] 2023-02-25 17:44
What's the status here?

**Closed** 2023-02-25 18:00 UTC
