### ISSUE TITLE
[Question] Configure Trino S3 with Nessie Catalog

### ISSUE THREAD

**Issue by domingozhang** [projectnessie/nessie#7764] opened 2023-11-27 01:21 UTC
**What happened**:
I configured Trino with Nessie catalog and S3 storage. The config file is as following:
connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.file-format=PARQUET
iceberg.nessie-catalog.uri=http://nessie_adress:19120/api/v1
iceberg.nessie-catalog.default-warehouse-dir=/tmp
nessie.s3.aws-access-key=aws-access-key
nessie.s3.aws-secret-key=aws-secret-key
nessie.s3.endpoint=http://s3endpoint/
nessie.s3.path-style-access=true
nessie.s3.ssl.enabled=false

I can run show catalogs and show tables, however, I was notified no S3 credential.

Query 20231127_011149_00003_trr72 failed: Error opening Iceberg split s3://nessie/dwd/table1/1ac9e7b8-aadf-50a1-83ce-efb541728900/3_0_0.parquet (offset=0, length=4210): Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@78b651a4: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@6437219b: Failed to connect to service endpoint: ]

I created a table under nessie catalog, but the files of table were created in /tmp 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by domingozhang** [comment] 2023-11-27 05:10
thanks @ajantha-bhat 

By following your suggestion, I modifed my configuration file as following:

connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.file-format=PARQUET
iceberg.nessie-catalog.uri=http://myadress:19120/api/v1
iceberg.nessie-catalog.default-warehouse-dir=s3://nessie02
s3.aws-access-key=access-key
s3.aws-secret-key=secret-key
s3.endpoint=http://endpoint
s3.path-style-access=true
s3.region=us-east-1
fs.native-s3.enabled=true

Now I can created table schema and table under s3://nessie02. But still failed when trying to insert value because of unable to load AWS credentials.
BTW, my S3 storage is DELL ECS. Did I miss any other configuration item?
Thanks in advance.


2023-11-27T12:52:23.719+0800    ERROR   stage-scheduler io.trino.execution.StageStateMachine    Stage 20231127_045221_00005_c7wf7.1 failed
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@17818445: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@2e85bc8: Failed to connect to service endpoint: ]

**Comment by domingozhang** [comment] 2023-11-28 03:39
My Trino Version is 433, which is the latest one. The config file is as following

```
connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.file-format=PARQUET
iceberg.nessie-catalog.uri=http://nessie_ip:19120/api/v1
iceberg.nessie-catalog.default-warehouse-dir=s3a://nessie
s3.aws-access-key=aws-access-key
s3.aws-secret-key=aws-secret-key
s3.endpoint=http://endpoint_adress
s3.path-style-access=true
s3.region=us-east-1
fs.native-s3.enabled=true
#s3.ssl.enabled=false
iceberg.nessie-catalog.ref=main
iceberg.register-table-procedure.enabled=true
```

In this version, if using hive.s3.item, will be errors.
```
1) Error: Configuration property 'hive.s3.aws-access-key' was not used

2) Error: Configuration property 'hive.s3.aws-secret-key' was not used

3) Error: Configuration property 'hive.s3.endpoint' was not used

4) Error: Configuration property 'hive.s3.path-style-access' was not used

5) Error: Configuration property 'hive.s3.region' was not used
```

Remove hive, trino can be started normally.


After I adjusted my configuration, still failed:

`Query 20231128_033054_00012_erzaj failed: Error opening Iceberg split s3://nessie02/test_trino/test_trino01-0ce32744f3924d9087977c5c803ba92d/1a9bda9d-1ea1-46d8-39eb-aed7d9e75100/3_0_0.parquet (offset=0, length=575): Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@17818445: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@2e85bc8: Failed to connect to service endpoint: ]`

**Comment by domingozhang** [comment] 2023-11-28 03:44
I can create or drop table in s3, but inert data or queries failed.

**Comment by snazy** [comment] 2023-11-29 08:13
Have you tried the suggestions in the error message and configure the environment variables or Java system properties?

**Comment by snazy** [comment] 2023-12-01 08:42
I'm going to close this issue, because it's not a bug. Happy to discuss Nessie related stuff further on https://project-nessie.zulipchat.com/

**Closed by snazy** 2023-12-01 08:42 UTC

**Comment by ajantha-bhat** [comment] 2023-12-13 16:51
@domingozhang: Have you followed up with the Trino community regarding (https://github.com/projectnessie/nessie/issues/7764#issuecomment-1831580114) ? Is the configurations clear now?

**Comment by VinothKumar0702** [comment] 2025-02-04 09:43
when i try to create an iceberg table for existing parquet file on s3

connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.file-format=PARQUET
iceberg.nessie-catalog.uri=http://localhost:19122/api/v1
iceberg.nessie-catalog.default-warehouse-dir=s3://warehouse
s3.aws-access-key=********************
s3.aws-secret-key=*********************
s3.endpoint=https://s3.endpoint.com
s3.path-style-access=true
s3.region=region
fs.native-s3.enabled=true
#s3.ssl.enabled=false
iceberg.nessie-catalog.ref=main
iceberg.register-table-procedure.enabled=true

when i comment on the s3 endpoint above configuration, I am able to create a table but can't create a table for existing file; instead, it create a new table in s3

**so how to create an iceberg table existing parquet file on an S3 bucket?**
I get this error:
Query 20250204_093546_00000_x5prz failed: Failed checking new table's location: s3://demo-007-snow/dataset.parquet
